### ISSUE TITLE
Graphic issues with SplitPane

### ISSUE THREAD

**Issue by ProtectedVariable** [orange451/LWJGUI#10]
Hi,

While redoing my GUI with your lib I've stumbled into two graphical issues regarding the usage of SplitPane.

First, when I do the following hierarchy: **SplitPane <- ScrollPane <- TreeView.** (Read "<-" as "contains") 
If I set the scroll pane to fill it's parent width and height (which I belive is the correct thing to do when a component must take the whole space it has in a SplitPane) the content of the tree takes the minimal amount of space it can (which is ok since we didn't set it to fill space) but if I set it to fill the space from it's parent I get the following glitch.

![Capture d’écran 2020-04-11 à 18 53 35](https://user-images.githubusercontent.com/1302694/79049789-e53f8180-7c25-11ea-892f-91edd1a6d229.png)

And when this happens I can also scoll to the right, making the text disappear even tought the text is smaller than the space inside the divider.

My second issue is when I put a StackPane in the middle of a SplitPane with two divisors, it seems that I can't get it to fill it's space (actually I wanted to put an OpenGL pane but to avoid errors comming from my use of the OpenGLPane I replaced it).
If I set to fill width / height to true I get the following result.

![Capture d’écran 2020-04-11 à 19 00 37](https://user-images.githubusercontent.com/1302694/79049921-c7bee780-7c26-11ea-94a7-ce5596679d8d.png)

Whereas if I just set it's pref size to a big enought number I get what I want

![Capture d’écran 2020-04-11 à 19 01 44](https://user-images.githubusercontent.com/1302694/79049937-efae4b00-7c26-11ea-97dd-a151adec077c.png)

The code the reproduce this is available here:
https://github.com/ProtectedVariable/ProtectedEngine/pull/19/files

The first issue mentionned is in HierarchyPane.java
The second one in at EditorLayout.java

(On a side note, is there a way to make the divisors of the splitpane thinner ?)

Hope my description is clear enough, feel free to ping me if more infos are needed :)

**Comment by orange451** [comment]
Thanks for all this info! I’ll play around with your examples and see if I can fix anything :)

**Comment by orange451** [comment]
I assume you want some functionality similar to this?
![image](https://user-images.githubusercontent.com/5247778/79057381-08bafa00-7c2f-11ea-92fc-4b433b29748b.png)

In order to make this, I removed the setFillToParentHeight() and setFillToParentWidth() calls in HierarchyPane.java

Then I overrode the position method like this:
`@Override
public void position(Node parent) {
	super.position(parent);
	
	sceneHierarchy.forceSize(this.getViewportWidth(), this.getViewportHeight());
}`

The reason being, the parent of sceneHierarchy is the CONTENT of the scrollpane, which is infinite size. So viewport must be used to make sure you size it to the correct element.

**Comment by orange451** [comment]
Also to answer your other question, you can use ScrollPane#setScrollBarThickness()

Also in the latest version, I added a scrollbar-width css property.

**Comment by ProtectedVariable** [comment]
Yep that's all good now, thanks a lot for your speedy response !

**Comment by ProtectedVariable** [comment]
Actually, there's just the remaining problem of the stackpane in the middle, if I set it to fill it's parent the whole layout gets weird, for now I just set it to have a big pref size but I don't know if that can cause issues in the future

**Comment by ProtectedVariable** [comment]
I've tired to use 
`@Override
    protected void position(Node parent) {
        super.position(parent);
        forceSize(parent.getWidth(), parent.getHeight());
    }`

In the OpenGL pane but while the parent width and height seems to be correct doing that messes up the layout 

![Capture d’écran 2020-04-12 à 14 56 36](https://user-images.githubusercontent.com/1302694/79069354-d6140e80-7ccd-11ea-9a63-28d4456267a4.png)

**Comment by ProtectedVariable** [comment]
Update: Actually not setting the size of the opengl pane seems to work in terms of layout but still, the clear happens everywhere but on the openglpane
