### ISSUE TITLE
TreeItem's text not affected by CSS

### ISSUE THREAD

**Issue by ProtectedVariable** [orange451/LWJGUI#12]
Hi,
It seems that TreeItems are not affected by stylesheets. At least the text doesn't seem to react to the color property.

**Comment by ProtectedVariable** [comment]
Actually it seems that all the content of a ScollPane is affected by this issue, maybe because of the setContent

**Comment by orange451** [comment]
Added treeitem css selector:
![image](https://i.imgur.com/euSoQm2.gif)
