### ISSUE TITLE
Key press events create new event objects for each node

### ISSUE THREAD

**Issue by Peanhua** [orange451/LWJGUI#15]
When multiple scene nodes have registered event handlers for key presses they all receive different event objects from the same physical key pressing event. This makes it impossible to use the "consumed" state of the event to signal when the event has been handled.

For example the following will print different addresses for the events and neither of them show the event as "consumed":
```
var a = new VBox();
a.setOnKeyPressed((event) -> {
    System.out.println("a=" + event + ", consumed=" + event.isConsumed());
    event.consume();
});
var b = new TextField();
b.setOnKeyPressed((event) -> {
    System.out.println("b=" + event + ", consumed=" + event.isConsumed());
    event.consume();
});
a.getChildren().add(b);
```
Output after pressing a key once:
```
a=lwjgui.event.KeyEvent@25d28510, consumed=false
b=lwjgui.event.KeyEvent@10297de3, consumed=false
```

The expected behavior is that both show same address for the event and one of them (the latter) shows the event as being "consumed".

**Comment by orange451** [comment]
Question to you, if the event is consumed, should it be passed to the child node?

**Comment by Peanhua** [comment]
The behavior should be that passing the event is stopped when someone consumes it.

The ```isConsumed()``` check can be done in the application code, but this check would need to be present on every event handler.

Also JavaFX stops passing the event when it is consumed, see the "capturing phase" in https://docs.oracle.com/javafx/2/events/processing.htm
The "bubbling phase" would be nice to have too :)

**Comment by orange451** [comment]
I pushed a change. It isn't exactly what you want, but it should help. Key events now all share the same event object, additionally the event is fired from the lowest descendant node and moves upwards towards the scene.

**Comment by orange451** [comment]
In the future I'll see if we can work to a more JavaFX styled event system.

**Comment by Peanhua** [comment]
Thanks :) It does help, sharing the same object is the most important thing, anything else can be worked around in the application code.

**Comment by Peanhua** [comment]
I am not sure if you wanted to keep this open or not, but from my point of view it can be closed.
