### ISSUE TITLE
TextField control receives KeyPress events when not in editing

### ISSUE THREAD

**Issue by Peanhua** [orange451/LWJGUI#16]
Not sure if this is intended behavior or not.

When a key is pressed, all the TextField controls receive the KeyPress event regardless of their editing state.

From applications point of view the key press events are relevant to a TextField control only when it is in editing mode. It is trivial to add code to check for ```isEditing()``` but it is extra lines of code, and the behavior here is unexpected and different from JavaFX.

**Comment by orange451** [comment]
Would you be okay with an implementation such that any node that either is selected or has a descendant that is selected will be passed the key events?

**Comment by Peanhua** [comment]
Sounds good :) There is always some root node that can "catch all" if needed.

**Comment by orange451** [comment]
Ok, this change is now pushed.

**Comment by Peanhua** [comment]
Thanks :) Works perfectly.
