### ISSUE TITLE
borderPane.setRight appears on the left side

### ISSUE THREAD

**Issue by Elime1** [orange451/LWJGUI#17]
Using master-SNAPSHOT

```
        lwjguiWindow = WindowManager.generateWindow(window);
        lwjguiWindow.setWindowAutoClear(false);

        Label label = new Label();
        label.setText("Right pane");

        StackPane stackPane = new StackPane();
        stackPane.setPrefWidth(100);
        stackPane.setFillToParentHeight(true);
        stackPane.setBackgroundLegacy(Color.WHITE);
        stackPane.getChildren().add(label);

        BorderPane borderPane = new BorderPane();
        borderPane.setRight(stackPane);

        Scene scene = lwjguiWindow.getScene();
        scene.setRoot(borderPane);
```
**Result:**
<img width="412" alt="border-pane-test" src="https://user-images.githubusercontent.com/9988754/86489490-c48a5200-bd64-11ea-8a7a-b8d78a093d45.png">

**Comment by orange451** [comment]
I am without my computer for a couple days. Can you try making the borderpane fill the parent (window) size? Also there is a BorderPaneTest in the tests package, can you reproduce this behavior in that example?

**Comment by Elime1** [comment]
Yes. It seems like it's dependent on the center being filled. If I comment out setCenter in the border pane test I get this:

<img width="432" alt="border-pane-example" src="https://user-images.githubusercontent.com/9988754/86520414-4b622c00-be44-11ea-8e43-173b120d30f6.png">

```
        @Override
	public void start(String[] args, Window window) {
		// Create a simple pane
		BorderPane pane = new BorderPane();
		
		// Put labels in the pane
		pane.setTop(new Label("top"));
		pane.setBottom(new Label("bottom"));
		//pane.setCenter(new Label("center"));
		pane.setLeft(new Label("left"));
		pane.setRight(new Label("right"));
		
		// Set the scene
		window.setScene(new Scene(pane, WIDTH, HEIGHT));
		window.show();
	}
```

**Comment by orange451** [comment]
Hey there! Thanks for your patience, this should not be fixed.

**Comment by Elime1** [comment]
It's working great. Thank you!
