### ISSUE TITLE
Add image on button

### ISSUE THREAD

**Issue by YEVGENIY1989** [orange451/LWJGUI#21]
Hi all. Can you tell me how i can add image on button?When i add image on button, image dont stay on center button, and when i turn on image, don't event button.

**Comment by orange451** [comment]
Hey! Do you have a picture example of what you’re looking to achieve? And can I see the code you tried so I can see what the problem is?

**Comment by YEVGENIY1989** [comment]
> Hey! Do you have a picture example of what you’re looking to achieve? And can I see the code you tried so I can see what the problem is?
> […](#)
> On Feb 4, 2021, at 2:17 AM, YEVGENIY1989 ***@***.***> wrote: ﻿ Hi all. Can you tell me how i can add image on button?When i add image on button, image dont stay on center button, and when i turn on image, don't event button. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I take you example ImageExample, and set image on button.  Image don't stay on center, and button no action when i click on image.
![button](https://user-images.githubusercontent.com/27804429/106925527-396da200-6721-11eb-8f60-b92d9071a335.PNG)
![code](https://user-images.githubusercontent.com/27804429/106925532-3a063880-6721-11eb-8824-ae96951ab176.PNG)

**Comment by orange451** [comment]
I just pushed a fix for the alignment issue in the Button class (in Labeled parent class).

As for click-through, please use `Node#setMouseTransparent()` method! Set to true for your graphic node, so it will not capture mouse input.

**Comment by YEVGENIY1989** [comment]
> I just pushed a fix for the alignment issue in the Button class (in Labeled parent class).
> 
> As for click-through, please use `Node#setMouseTransparent()` method! Set to true for your graphic node, so it will not capture mouse input.

Hello. This solved my problem. Thanks for finding a solution quickly.
