### ISSUE TITLE
Custom widget?

### ISSUE THREAD

**Issue by adhxtry** [orange451/LWJGUI#24]
I want to create some custom widgets for my project. Where I can find **example** to that? Or if example not possible please let me know the method. So basically just like any other gui lib we either have a **paint method** inside component class like qt and swing or we have something like **skin classes** like javafx. It would be great if you can tell me which classes to look up for understanding how components are exactly made.
*<p align="center">Thanks!</p>*

**Comment by orange451** [comment]
Hello!

You can either extend existing controls, extend the Control class yourself, extend Pane, or extend Node to create your own widgets.

Node is the base-level object in the scenegraph, and it does have render capability, just extend the render method!

**Comment by adhxtry** [comment]
Excellent! Thanks sir.
