### ISSUE TITLE
Add a slider

### ISSUE THREAD

**Issue by SIsilicon** [orange451/LWJGUI#3]
Firstly I would love to thank you for making this. I find this quite resourceful.
I would like to suggest an additional control to the library. *A slider*. I'm making a 3D game engine, and I need a slider for changing values such as material roughness and light brightness.

**Comment by orange451** [comment]
Sure thing!

**Comment by orange451** [comment]
I had some time today and implemented a basic slider. It should hopefully be enough for simple sliders like your material/lighting information.

I'll work on a more robust and feature complete one in the future; however how it's used wont be changed (Your code wont break).

**Comment by SIsilicon** [comment]
Thank you very much sir/madam! :-)
I'll be sure to send you a screenshot. It isn't much right now, and I'm kinda focusing on the graphics aspect right now.

**Comment by SIsilicon** [comment]
Hey, I tried out the slider, but my IDE is complaining about it not even existing. And when I try to build it myself, it says that it can't load any fonts on runtime (Which actually never came with the src folder).

**Comment by SIsilicon** [comment]
While I'm talking, could you tell me how to build this project from source? In case there are other bugs I could fix myself.

**Comment by orange451** [comment]
I’ve never used netbeans. The project is in maven format, so your best bet would be to google how to compile a jar from a maven project.

While it is not correct, you CAN copy both SRC folders into each other (main src and resources src), then compile like a normal java project. But again, it’s not the correct way to compile maven projects.

**Comment by SIsilicon** [comment]
Well I managed to compile myself, and the buttons now working. Thanks for your help.

**Comment by SIsilicon** [comment]
![my engine](https://i.imgur.com/FGBBgE0_d.jpg?maxwidth=640&shape=thumb&fidelity=high)
Here it is. The current features are:
- Point, Spot and Directional Lights

- Shadows from said lights

- Volumetrics

- Physically based materials

- Sorted Transparency

- Normal and Deep Parallax mapping

- Loading external models, shaders and other resources

**Comment by orange451** [comment]
Do you have discord? I'd like to have some conversations with you from time to time :)
Mine is: NovaStrat#2111

**Comment by SIsilicon** [comment]
Nah, I don't have one. But I do have Gmail.

**Comment by SIsilicon** [comment]
Ok. Now I have a discord.
SI Silicon #6053
