### ISSUE TITLE
Gradle setup

### ISSUE THREAD

**Issue by hohserg1** [orange451/LWJGUI#4]
Hello! I'm want to use your library - LWJGUI, but I dont found way to added it to my gradle project. However, I can use jitpack and added dependecy  by github repo, but I dont know what commit or branch is stable/release.
Can you help me for this?
Thanks in advance!

**Comment by orange451** [comment]
The main branch is stable.

I’ve never used gradle, so I don’t think I can be of much help.

**Comment by hohserg1** [comment]
Thx you! I'm write instructions for gradle later
