### ISSUE TITLE
Image

### ISSUE THREAD

**Issue by Aryesia** [orange451/LWJGUI#8]
Hello! I develop project with your library LWJGUI and i have questions.
I try set image from resources to button, but i get error "java.io.FileNotFoundException". 

![image](https://user-images.githubusercontent.com/55660158/71992713-70e0f500-3268-11ea-9c21-fe163583910f.png)

I try
![image](https://user-images.githubusercontent.com/55660158/71992569-2790a580-3268-11ea-9a3c-9071120fbae1.png)
and similar solutions, but the result remains the same...
Help me please or send me documentation.
Thank you

**Comment by Guerra24** [comment]
Okay, I don't know if this still an issue but regardless.
The Image accepts a relative or absolute path. The code will try to detect if the file is inside or outside the jar. In this case I see the file is inside the jar so the path should be relative to the `src/main/resources`(or whatever path is treated as resources) i.e. it should be `ui/message_icon.png`.
