### ISSUE TITLE
I can't import  LWJGUI  in maven

### ISSUE THREAD

**Issue by GarnicaJR** [orange451/LWJGUI#9]
Hi all,

Yesterday I tried import the library in a maven project but i am getting the message shown below
```
[ERROR] Failed to execute goal on project wglw: Could not resolve dependencies for project org.example:wglw:jar:1.0-SNAPSHOT: Failure to find com.github.orange451:
LWJGUI:jar:Tag in https://jitpack.io was cached in the local repository, resolution will not be reattempted until the update interval of jitpack.io has elapsed or
updates are forced -> [Help 1]
[ERROR]

```

POM.xml
```

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>wglw</artifactId>
    <version>1.0-SNAPSHOT</version>


    <repositories>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>

    <dependencies>

        <dependency>
            <groupId>com.github.orange451</groupId>
            <artifactId>LWJGUI</artifactId>
            <version>Tag</version>
        </dependency>
    </dependencies>

</project>
```

I have executed this command from terminal 
`mvn clean install`

The project is empty so i dont know why i can't import the library.

**Comment by orange451** [comment]
I believe the jitpack info is out-dated and no longer works. LWJGUI is now a gradle project. Before it came as a pre-packaged jar, but not anymore.

**Comment by orange451** [comment]
See this link: https://dzone.com/articles/how-to-convert-maven-to-gradle-and-vice-versa

**Comment by Guerra24** [comment]
Version value is incorrect, it needs to be `master-SNAPSHOT` or a commit hash.

**Comment by GarnicaJR** [comment]
> Version value is incorrect, it needs to be `master-SNAPSHOT` or a commit hash.

gotcha, i will try that more later ,

thanks,

**Comment by GarnicaJR** [comment]
> I believe the jitpack info is out-dated and no longer works. LWJGUI is now a gradle project. Before, it came as a pre-packaged jar, but not anymore. Will check with @Guerra24

so do you recommend avoid use jitpack for a new project?

**Comment by orange451** [comment]
If you can get it to work, then it'll be fine. The code base you get from that is the same one you get from cloning directly from github via gradle.

**Comment by orange451** [comment]
Was your issue solved?

**Comment by zdg-kinlon** [comment]
```xml
<repositories>
    <repository>
        <id>jitpack.io</id>
        <url>https://jitpack.io</url>
    </repository>
</repositories>

<dependencies>
    <dependency>
        <groupId>com.github.orange451</groupId>
        <artifactId>LWJGUI</artifactId>
	<version>pre-mt</version>
    </dependency>
</dependencies>
```
